name = "Sunrise Hub"
license = "MIT"
licenselink = "https://github.com/sunrise-bay-area/sunrise-hub/blob/main/LICENSE"
description = "Sunrise Hub Hugo Theme"
homepage = "https://github.com/sunrise-bay-area/sunrise-hub"
tags = ['netlify', 'responsive', 'dark', 'lightweight']
features = ['banner', 'netlify']
min_version = "0.41"

[[authors]]
   [author.brooke]
     name = "Brooke Angel"
     homepage = "http://brookeangel.github.io/"

   [author.alex]
     name = "Alex Rosengarten"
     homepage = "https://alxrsngrtn.com/"

   [author.ahlad]
    name = "Ahlad Reddy"
    homepage = "https://babydangerlove.substack.com/"

